config:
    fallback-icon: "?"
    show-name: false

icons:
    nvim: "ğŸ“"
    stripe: "ğŸ’³"
    stripe-mock: "ğŸ’³"
    btop: "ğŸ“ˆ"
    bun: "ğŸ¥Ÿ"
    zsh: "î¢" # overwrite with your own symbol (Nerd Font icon, emoji, whatever!)
